### ISSUE TITLE
Can only use one tag

### ISSUE THREAD

**Issue by Cryonyx** [robbyedwards/octopress-tag-pages#3]
```
layout: post
title: "Hello World"
date: 2013-07-29 20:12
comments: true
categories: [Misc, Hello World]
description: Hello World
tags: Misc
```

This works fine, but if add another tag, like the categories above:
    tags: [Misc, HelloWorld]
when `rake generate` I got Build Failed
    Liquid Exception: comparison of Array with Array failed in page

full info is below:

```
## Generating Site with Jekyll
[31m[0m[32midentical[0m source/stylesheets/screen.css 
Configuration from /home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/_config.yml
Building site: source -> public
Liquid Exception: comparison of Array with Array failed in page
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/tag_cloud.rb:76:in `sort!'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/tag_cloud.rb:76:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:82:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/template.rb:124:in `render'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:45:in `block (3 levels) in render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/context.rb:91:in `stack'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:44:in `block (2 levels) in render'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:39:in `chdir'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:39:in `block in render'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:34:in `each'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/include_array.rb:34:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/if.rb:39:in `block (2 levels) in render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/if.rb:37:in `each'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/if.rb:37:in `block in render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/context.rb:91:in `stack'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/if.rb:36:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/unless.rb:16:in `block in render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/context.rb:91:in `stack'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/tags/unless.rb:11:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `collect'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/block.rb:82:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/template.rb:124:in `render'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/liquid-2.3.0/lib/liquid/template.rb:132:in `render!'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:101:in `do_layout'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/post_filters.rb:167:in `do_layout'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/page.rb:100:in `render'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/category_generator.rb:93:in `write_category_index'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/category_generator.rb:111:in `block in write_category_indexes'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/category_generator.rb:110:in `each'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/category_generator.rb:110:in `write_category_indexes'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/category_generator.rb:139:in `generate'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:190:in `block in generate'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:189:in `each'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:189:in `generate'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:40:in `process'
/home/twtwtw/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
/home/twtwtw/.rbenv/versions/1.9.3-p194/bin/jekyll:23:in `load'
/home/twtwtw/.rbenv/versions/1.9.3-p194/bin/jekyll:23:in `<main>'
Build Failed

```

**Comment by jeromesun14** [comment]
I got the same problem, but I have no idea with ruby.

**Comment by EpsilonX** [comment]
I got the same problem, too

**Comment by csutherl** [comment]
That has nothing to do with the tag-pages plugin, its failing in the build of the tag-cloud, note the exception references tag_cloud.rb, line 76:

```
Liquid Exception: comparison of Array with Array failed in page
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/tag_cloud.rb:76:in `sort!'
```

The problem is captured in https://github.com/robbyedwards/octopress-tag-cloud/issues/1. I submitted a pull request to resolve the issue yesterday :) Check it out and see if it resolves the problem for you if you are still experiencing it...

**Comment by taringamberini** [comment]
This issue can be closed.

In fact the problem issued by @Cryonyx is about [`octopress-tag-clouds`](https://github.com/robbyedwards/octopress-tag-cloud) plugin as reported in the log:

```
## Generating Site with Jekyll
�[31m�[0m�[32midentical�[0m source/stylesheets/screen.css 
Configuration from /home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/_config.yml
Building site: source -> public
Liquid Exception: comparison of Array with Array failed in page
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/tag_cloud.rb:76:in `sort!'
/home/twtwtw/Projects/Websites/Cryo-Nyx.Blog/plugins/tag_cloud.rb:76:in `render'
```

while the plugin of this project is `tag_generator.rb`.

Two solutions of this problem yet exists:
1. https://github.com/robbyedwards/octopress-tag-cloud/pull/5 which ends up in 100% font size
2. https://github.com/robbyedwards/octopress-tag-cloud/issues/1 which ends up in 170% font size
